# Generated by Django 4.1.5 on 2023-01-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ManyToManyField(related_name='blogs', to='blog.blog')),
                ('category', models.ManyToManyField(related_name='categories', to='blog.category')),
            ],
        ),
    ]
