# Generated by Django 4.1.5 on 2023-01-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Hashtag',
            field=models.ManyToManyField(related_name='Hashtags', to='blog.hashtag'),
        ),
        migrations.AddField(
            model_name='category',
            name='Hashtag',
            field=models.ManyToManyField(related_name='hashtags', to='blog.hashtag'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title',
            field=models.CharField(default='txt', max_length=200),
            preserve_default=False,
        ),
    ]
